import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const translations = {
  he: {
    dir: 'rtl',
    // Language picker
    langPickerTitle: 'שפת האפליקציה',
    langPickerSubtitle: 'בחר את השפה שלך',
    langPickerContinue: 'המשך',
    hebrew: 'עברית',
    arabic: 'עברית',

    // Landing
    skip: 'דלג',
    next: 'הבא',
    joinMovement: 'הצטרף לתנועה 🌿',
    alreadyHaveAccount: 'כבר יש לך חשבון?',
    signIn: 'התחבר',

    // Landing slides
    slides: [
      { title: 'שני עמים.\nעולם אחד.', body: 'ישראלים ופלסטינים חיים זה לצד זה מזה דורות — אך רובם מעולם לא קיימו שיחה אמיתית. QOL משנה את זה.' },
      { title: 'התחבר מעבר\nלגבול.', body: 'גלה אנשים אמיתיים בצד השני. החלק, התאם ופתח שיחה — מתורגמת אוטומטית כדי שהשפה לא תהיה מחסום.' },
      { title: 'כל הודעה\nהיא גשר.', body: 'שלום לא מתחיל בפרלמנטים. הוא מתחיל ב"שלום" פשוט בין שני בני אדם סקרנים.' },
      { title: 'בטוח.\nמכבד.\nאמיתי.', body: 'QOL נבנה עם תכונות בטיחות קפדניות לקטינים ומבוגרים כאחד. קהילה המושרשת בכבוד הדדי.' },
    ],

    // Auth
    signInTitle: 'ברוך שובך',
    signInSubtitle: 'מחבר אנשים, גשר בין עולמות',
    signInBtn: 'התחבר',
    signingIn: 'מתחבר…',
    emailLabel: 'אימייל',
    passwordLabel: 'סיסמה',
    confirmPasswordLabel: 'אשר סיסמה',
    forgotPassword: 'שכחת סיסמה?',
    noAccount: 'אין לך חשבון?',
    signUp: 'הירשם',
    signUpTitle: 'צור חשבון',
    signUpSubtitle: 'הצטרף לקהילת QOL',
    createAccount: 'צור חשבון',
    creatingAccount: 'יוצר חשבון…',
    alreadyHaveAccount: 'כבר יש לך חשבון?',
    ageDisclaimer: 'בהרשמה אתה מאשר שאתה בן לפחות 14.',
    passwordMismatch: 'הסיסמאות אינן תואמות',
    passwordTooShort: 'הסיסמה חייבת להכיל לפחות 6 תווים',

    // OTP
    checkEmail: 'בדוק את האימייל שלך',
    otpSentTo: 'שלחנו קוד אימות ל-',
    enterCode: 'הכנס קוד בן 6 ספרות',
    verify: 'אמת',
    verifying: 'מאמת…',
    resendCode: 'שלח קוד מחדש',
    codeResent: 'הקוד נשלח מחדש!',

    // Onboarding
    continue: 'המשך',
    whatsYourName: 'מה שמך?',
    nameSubtitle: 'כך משתמשים אחרים יראו אותך.',
    namePlaceholder: 'השם הפרטי שלך',
    whoAreYou: 'מי אתה?',
    nationalitySubtitle: 'הלאומיות שלך קובעת את השפה באפליקציה.',
    aboutYouTitle: 'קצת עליך',
    aboutYouSubtitle: 'ספר לנו קצת על עצמך.',
    gender: 'מגדר',
    male: 'זכר',
    female: 'נקבה',
    other: 'אחר',
    dateOfBirth: 'תאריך לידה',
    mustBe14: 'חייב להיות בן לפחות 14.',
    selectGender: 'בחר מגדר',
    enterBirthdate: 'הכנס תאריך לידה',
    notOldEnough: 'חייב להיות בן לפחות 14 להצטרף ל-QOL.',
    interestsTitle: 'תחומי העניין שלך',
    interestsSubtitle: 'בחר לפחות 3 תחביבים. הם עוזרים לך להתחבר עם אנשים שחולקים את התשוקות שלך.',
    selected: 'נבחרו',
    needMore: 'עוד נדרשים',
    yourProfileTitle: 'הפרופיל שלך',
    yourProfileSubtitle: 'הוסף תמונה וביו כדי שאנשים יוכלו להכיר אותך.',
    tapToAddPhoto: 'לחץ להוסיף תמונת פרופיל',
    bioLabel: 'ביו',
    bioOptional: '(אופציונלי)',
    bioPlaceholder: 'כמה מילים עליך — תחביבים, עיר, מה אתה מחפש בחיבור…',
    completeProfile: 'סיים פרופיל',
    skipForNow: 'דלג לעכשיו',

    // Tabs
    discover: 'גלה',
    matches: 'התאמות',
    games: 'משחקים',
    profile: 'פרופיל',

    // Matches page
    matchesTitle: 'התאמות',
    connections: 'חיבורים',
    connection: 'חיבור',
    noMatchesYet: 'אין התאמות עדיין',
    noMatchesMsg: 'התחל להחליק בלשונית הגילוי כדי למצוא את החיבור הבין-תרבותי הראשון שלך!',
    goToDiscover: 'עבור לגילוי',
    newMatch: 'התאמה חדשה!',

    // Games page
    miniGamesTitle: 'מיני משחקים',
    learnTogether: 'למד שפה יחד עם ההתאמה שלך',
    chooseGame: 'בחר משחק',
    pickMatch: 'בחר התאמה לשחק איתה',
    noMatchesForGame: 'אתה צריך לפחות התאמה אחת כדי לשחק!',
    noMatchesOnline: 'אין התאמות מחוברות כעת. נסה שוב מאוחר יותר!',
    selectGameHint: 'בחר משחק למעלה כדי להתחיל!',
    playWith: 'שחק',
    twoPlayerGames: 'משחקים לשניים',
    pendingInvites: 'הזמנות ממתינות',
    invitedYou: 'הזמין/ה אותך ל',
    acceptInvite: 'קבל ושחק',
    waitingForOpponent: 'ממתין שהיריב יצטרף…',
    inviteSent: 'ההזמנה נשלחה אל',
    cancel: 'ביטול',

    // Offline / letter match game
    offlineGames: 'משחקים לשחקן יחיד',
    letterMatchName: 'התאם אותיות',
    letterMatchDesc: 'גרור אותיות עברית וערבית לזוגות — לשחקן יחיד',
    matchLettersTitle: 'התאם אותיות',
    howToPlay: 'איך משחקים:',
    howToPlayDesc: 'גרור כל אות אל האות התואמת בשפה השנייה. הקש על אות כדי לשמוע אותה. 3 טעויות והמשחק נגמר.',
    gotIt: 'הבנתי!',
    youDidIt: 'עשית את זה!',
    allMatched: 'כל האותיות הותאמו בהצלחה.',
    playAgain: 'שחק שוב',
    youLost: 'הפסדת',
    lostDesc: 'עשית 3 טעויות. לא נורא, אפשר לנסות שוב!',

    // Memory game
    localTwoPlayerGames: 'משחקים מקומיים לשניים',
    memoryGameName: 'משחק הזיכרון',
    memoryGameDesc: 'הפוך קלפים והתאם זוגות — שני שחקנים באותו מכשיר',
    memoryGameTitle: 'משחק הזיכרון',
    player: 'שחקן',
    player1: 'שחקן 1',
    player2: 'שחקן 2',
    playerTurn: 'תור שחקן',
    tie: 'תיקו!',
    winner: 'מנצח',
    yourTurn: 'תורך!',

    // Profile page
    profileTitle: 'פרופיל',
    signOut: 'התנתק',
    aboutMe: 'עלי',
    interests: 'תחומי עניין',
    noBio: 'אין ביו עדיין. לחץ ✏️ להוסיף.',
    noInterests: 'אין תחומי עניין עדיין.',
    appLanguage: 'שפת האפליקציה',
    writeSomething: 'כתוב משהו על עצמך…',
    needThreeMore: 'נדרשים עוד',
    minor: '🔒 קטין',
    adult: '✓ מבוגר',
    yearsOld: 'שנים',

    // Hobby translations
    hobbyTranslations: { Music: 'מוזיקה', Art: 'אמנות', Cooking: 'בישול', Reading: 'קריאה', Football: 'כדורגל', Basketball: 'כדורסל', Tennis: 'טניס', Swimming: 'שחייה', Hiking: 'טיול', Photography: 'צילום', Gaming: 'גיימינג', Dancing: 'ריקוד', Travel: 'טיול', Yoga: 'יוגה', Fitness: 'כושר', Cinema: 'קולנוע', Theatre: 'תיאטרון', Poetry: 'שירה', Chess: 'שחמט', Cycling: 'רכיבה', Painting: 'ציור', Volunteering: 'התנדבות', Languages: 'שפות', History: 'היסטוריה', Technology: 'טכנולוגיה' },

    // Nationality labels
    israeli: 'ישראלי',
    palestinian: 'פלסטיני',

    // Swipe actions
    like: 'לייק',
    pass: 'פסס',
    interests: 'תחומי עניין',
    stillExploring: 'עדיין מגלה תחביבים',
    findingConnections: 'מוצא חיבורים…',

    // Mini games
    wordGuessName: 'ניחוש מילים',
    wordGuessDesc: 'נחש את המילה בשפה השנייה. בתורות!',
    translationDuelName: 'דו-קרב תרגום',
    translationDuelDesc: 'תרגם משפט — השותף שלך מדרג את תשובתך!',

    // Discover
    discoverTitle: 'גלה',
    meeting: 'פגישה עם',
    palestinians: 'פלסטינים',
    israelis: 'ישראלים',
    filter: 'סנן',
    all: 'הכל',
    sayHello: 'אמור שלום!',
    autoTranslated: 'מתורגם אוטומטית.',
    youMetEveryone: 'פגשת את כולם!',
    comeBackSoon: 'עברת על כל החיבורים הזמינים. אנשים חדשים מצטרפים כל יום — חזור בקרוב!',
    refresh: 'רענן',

    // Chat
    autoTranslatedMsg: 'מתורגם אוטומטית',
    translationOff: 'תרגום כבוי',
    clearChat: 'נקה צ\'אט?',
    clearChatMsg: 'כל ההודעות יימחקו לצמיתות עבור שני המשתמשים.',
    cancel: 'ביטול',
    clear: 'נקה',
    writeHere: '…כתוב בעברית',

    // Game room
    opponent: 'יריב',
    roundOf: 'סיבוב',
    of: 'מתוך',
    you: 'אתה',
    finalScore: 'תוצאה סופית',
    playAgain: 'שחק שוב',
    itsDraw: "תיקו!",
    youWon: '🎉 ניצחת!',
    goodGame: 'משחק טוב!',
    opponentLeft: 'היריב עזב את המשחק',
    opponentLeftDesc: 'המשחק הסתיים מכיוון שהשחקן השני עזב.',
    backToGames: 'חזור למשחקים',
    won: 'ניצח',
    wordGuessGameName: '🔤 ניחוש מילים',
    translationDuelGameName: '⚔️ דו-קרב תרגום',

    // Word Guess game
    translateToLang: 'תרגם מילה זו ל',
    arabic: 'ערבית',
    hebrew: 'עברית',
    typeAnswerIn: 'הקלד תשובתך ב',
    answerIn: 'תשובה ב',
    submitBtn: 'שלח',
    yourAnswer: 'התשובה שלך',
    waitingFor: 'ממתין ל',
    correctAnswer: 'תשובה נכונה',
    answered: '✅ ענה',
    thinking: '⏳ חושב…',

    // Translation Duel
    translateTo: 'תרגם ל',
    writeTranslationIn: 'כתוב את התרגום שלך ב',
    yourTranslationIn: 'התרגום שלך ב',
    submitTranslation: 'שלח תרגום',
    yourTranslation: 'התרגום שלך',
    translationOf: 'תרגום של',
    reference: 'עזר',
    rateTranslation: 'דרג את התרגום של',
    close: 'קרוב',
    good: 'טוב',
    perfect: 'מושלם',
    ratingsThisRound: 'דירוגים בסיבוב זה',
    youGot: 'קיבלת',
    got: 'קיבל',
    nextRound: 'הסיבוב הבא מגיע…',
    submitted: '✅ שלח',
    writing: '⏳ כותב…',
  },

  ar: {
    dir: 'rtl',
    // Language picker
    langPickerTitle: 'لغة التطبيق',
    langPickerSubtitle: 'اختر لغتك',
    langPickerContinue: 'استمر',
    hebrew: 'عربي',
    arabic: 'عربي',

    // Landing
    skip: 'تخطى',
    next: 'التالي',
    joinMovement: 'انضم للحركة 🌿',
    alreadyHaveAccount: 'هل لديك حساب؟',
    signIn: 'سجل دخول',

    // Landing slides
    slides: [
      { title: 'شعبان.\nعالم واحد.', body: 'عاش الإسرائيليون والفلسطينيون جنباً إلى جنب لأجيال — لكن معظمهم لم يجروا محادثة حقيقية قط. QOL يغيّر ذلك.' },
      { title: 'تواصل عبر\nالحدود.', body: 'اكتشف أشخاصاً حقيقيين على الجانب الآخر. مرّر، تطابق وابدأ محادثة — تُترجم تلقائياً حتى لا تكون اللغة عائقاً.' },
      { title: 'كل رسالة\nهي جسر.', body: 'السلام لا يبدأ في البرلمانات. يبدأ بـ"مرحباً" بسيطة بين إنسانَين فضوليَّين.' },
      { title: 'آمن.\nمحترم.\nحقيقي.', body: 'QOL مبني بميزات أمان صارمة للقاصرين والبالغين على حدٍّ سواء. مجتمع متجذّر في الاحترام المتبادل.' },
    ],

    // Auth
    signInTitle: 'مرحباً بعودتك',
    signInSubtitle: 'يربط الناس ويجسر العوالم',
    signInBtn: 'تسجيل الدخول',
    signingIn: 'جارٍ تسجيل الدخول…',
    emailLabel: 'البريد الإلكتروني',
    passwordLabel: 'كلمة المرور',
    confirmPasswordLabel: 'تأكيد كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟',
    signUp: 'سجّل',
    signUpTitle: 'إنشاء حساب',
    signUpSubtitle: 'انضم إلى مجتمع QOL',
    createAccount: 'إنشاء حساب',
    creatingAccount: 'جارٍ إنشاء الحساب…',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    ageDisclaimer: 'بالتسجيل، تؤكد أن عمرك 14 سنة على الأقل.',
    passwordMismatch: 'كلمتا المرور غير متطابقتين',
    passwordTooShort: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',

    // OTP
    checkEmail: 'تحقق من بريدك الإلكتروني',
    otpSentTo: 'أرسلنا رمز التحقق إلى ',
    enterCode: 'أدخل الرمز المكون من 6 أرقام',
    verify: 'تحقق',
    verifying: 'جارٍ التحقق…',
    resendCode: 'إعادة إرسال الرمز',
    codeResent: 'تم إعادة إرسال الرمز!',

    // Onboarding
    continue: 'استمر',
    whatsYourName: 'ما اسمك؟',
    nameSubtitle: 'هكذا سيراك المستخدمون الآخرون.',
    namePlaceholder: 'اسمك الأول',
    whoAreYou: 'من أنت؟',
    nationalitySubtitle: 'تحدد جنسيتك اللغة في التطبيق.',
    aboutYouTitle: 'عنك',
    aboutYouSubtitle: 'أخبرنا قليلاً عن نفسك.',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    other: 'آخر',
    dateOfBirth: 'تاريخ الميلاد',
    mustBe14: 'يجب أن يكون عمرك 14 سنة على الأقل.',
    selectGender: 'اختر الجنس',
    enterBirthdate: 'أدخل تاريخ الميلاد',
    notOldEnough: 'يجب أن يكون عمرك 14 سنة على الأقل للانضمام إلى QOL.',
    interestsTitle: 'اهتماماتك',
    interestsSubtitle: 'اختر 3 هوايات على الأقل. تساعدك على التواصل مع الأشخاص الذين يشاركونك شغفك.',
    selected: 'محدد',
    male: 'ذكر',
    female: 'أنثى',
    other: 'آخر',
    needMore: 'مطلوب المزيد',
    yourProfileTitle: 'ملفك الشخصي',
    yourProfileSubtitle: 'أضف صورة ونبذة حتى يتعرف عليك الناس.',
    tapToAddPhoto: 'اضغط لإضافة صورة الملف الشخصي',
    bioLabel: 'نبذة',
    bioOptional: '(اختياري)',
    bioPlaceholder: 'بضع كلمات عنك — هواياتك، مدينتك، ما تبحث عنه في تواصل…',
    completeProfile: 'إكمال الملف الشخصي',
    skipForNow: 'تخطى الآن',

    // Tabs
    discover: 'اكتشف',
    matches: 'التطابقات',
    games: 'الألعاب',
    profile: 'الملف الشخصي',

    // Matches page
    matchesTitle: 'التطابقات',
    connections: 'اتصالات',
    connection: 'اتصال',
    noMatchesYet: 'لا تطابقات بعد',
    noMatchesMsg: 'ابدأ بالتمرير في علامة الاكتشاف للعثور على أول تواصل عابر للثقافات!',
    goToDiscover: 'اذهب للاكتشاف',
    newMatch: 'تطابق جديد!',

    // Games page
    miniGamesTitle: 'الألعاب المصغرة',
    learnTogether: 'تعلم لغة مع تطابقك',
    chooseGame: 'اختر لعبة',
    pickMatch: 'اختر تطابقاً للعب معه',
    noMatchesForGame: 'تحتاج إلى تطابق واحد على الأقل للعب!',
    noMatchesOnline: 'لا يوجد تطابقات متصلون الآن. حاول مرة أخرى لاحقاً!',
    selectGameHint: 'اختر لعبة من أعلى للبدء!',
    playWith: 'العب',
    twoPlayerGames: 'ألعاب للاعبين',
    pendingInvites: 'دعوات معلّقة',
    invitedYou: 'دعاك إلى',
    acceptInvite: 'اقبل والعب',
    waitingForOpponent: 'في انتظار انضمام الخصم…',
    inviteSent: 'تم إرسال الدعوة إلى',
    cancel: 'إلغاء',

    // Offline / letter match game
    offlineGames: 'ألعاب للاعب واحد',
    letterMatchName: 'طابق الحروف',
    letterMatchDesc: 'اسحب الحروف العبرية والعربية لتطابقها — للاعب واحد',
    matchLettersTitle: 'طابق الحروف',
    howToPlay: 'كيفية اللعب:',
    howToPlayDesc: 'اسحب كل حرف إلى الحرف المطابق باللغة الأخرى. اضغط على حرف لسماع نطقه. 3 أخطاء تنهي اللعبة.',
    gotIt: 'فهمت!',
    youDidIt: 'أحسنت!',
    allMatched: 'تمت مطابقة جميع الحروف بنجاح.',
    playAgain: 'العب مرة أخرى',
    youLost: 'خسرت',
    lostDesc: 'لقد أخطأت 3 مرات. لا بأس، يمكنك المحاولة مرة أخرى!',

    // Memory game
    localTwoPlayerGames: 'ألعاب محلية للاعبين',
    memoryGameName: 'لعبة الذاكرة',
    memoryGameDesc: 'اقلب البطاقات وطابق الأزواج — لاعبان على نفس الجهاز',
    memoryGameTitle: 'لعبة الذاكرة',
    player: 'لاعب',
    player1: 'لاعب 1',
    player2: 'لاعب 2',
    playerTurn: 'دور اللاعب',
    tie: 'تعادل!',
    winner: 'فاز',
    yourTurn: 'دورك!',

    // Profile page
    profileTitle: 'الملف الشخصي',
    signOut: 'تسجيل الخروج',
    aboutMe: 'عني',
    interests: 'الاهتمامات',
    noBio: 'لا توجد نبذة بعد. اضغط ✏️ للإضافة.',
    noInterests: 'لا توجد اهتمامات بعد.',
    appLanguage: 'لغة التطبيق',
    writeSomething: 'اكتب شيئاً عن نفسك…',
    needThreeMore: 'مطلوب المزيد',
    minor: '🔒 قاصر',
    adult: '✓ بالغ',
    yearsOld: 'سنة',

    // Hobby translations
    hobbyTranslations: { Music: 'موسيقى', Art: 'فن', Cooking: 'طبخ', Reading: 'قراءة', Football: 'كرة قدم', Basketball: 'كرة سلة', Tennis: 'تنس', Swimming: 'سباحة', Hiking: 'مشي', Photography: 'تصوير', Gaming: 'ألعاب', Dancing: 'رقص', Travel: 'سفر', Yoga: 'يوغا', Fitness: 'لياقة', Cinema: 'سينما', Theatre: 'مسرح', Poetry: 'شعر', Chess: 'شطرنج', Cycling: 'دراجات', Painting: 'رسم', Volunteering: 'تطوع', Languages: 'لغات', History: 'تاريخ', Technology: 'تقنية' },

    // Nationality labels
    israeli: 'إسرائيلي',
    palestinian: 'فلسطيني',

    // Swipe actions
    like: 'إعجاب',
    pass: 'تخطى',
    interests: 'الاهتمامات',
    stillExploring: 'لا يزال يستكشف الاهتمامات',
    findingConnections: 'جارٍ البحث عن اتصالات…',

    // Mini games
    wordGuessName: 'تخمين الكلمات',
    wordGuessDesc: 'خمّن الكلمة باللغة الأخرى. بالتناوب!',
    translationDuelName: 'مبارزة الترجمة',
    translationDuelDesc: 'ترجم جملة — شريكك يقيّم إجابتك!',

    // Discover
    discoverTitle: 'اكتشف',
    meeting: 'التعرف على',
    palestinians: 'فلسطينيين',
    israelis: 'إسرائيليين',
    filter: 'تصفية',
    all: 'الكل',
    sayHello: 'قل مرحباً!',
    autoTranslated: 'تُترجم تلقائياً.',
    youMetEveryone: 'قابلت الجميع!',
    comeBackSoon: 'لقد مررت على جميع الاتصالات المتاحة. ينضم أشخاص جدد كل يوم — عد قريباً!',
    refresh: 'تحديث',

    // Chat
    autoTranslatedMsg: 'مترجم تلقائياً',
    translationOff: 'الترجمة معطّلة',
    clearChat: 'مسح المحادثة؟',
    clearChatMsg: 'ستُحذف جميع الرسائل نهائياً لكلا المستخدمَين.',
    cancel: 'إلغاء',
    clear: 'مسح',
    writeHere: 'اكتب بالعربية…',

    // Game room
    opponent: 'خصم',
    roundOf: 'جولة',
    of: 'من',
    you: 'أنت',
    finalScore: 'النتيجة النهائية',
    playAgain: 'العب مجدداً',
    itsDraw: 'تعادل!',
    youWon: '🎉 فزت!',
    goodGame: 'لعبة جيدة!',
    opponentLeft: 'غادر الخصم اللعبة',
    opponentLeftDesc: 'انتهت اللعبة لأن اللاعب الآخر غادر.',
    backToGames: 'العودة إلى الألعاب',
    won: 'فاز',
    wordGuessGameName: '🔤 تخمين الكلمات',
    translationDuelGameName: '⚔️ مبارزة الترجمة',

    // Word Guess game
    translateToLang: 'ترجم هذه الكلمة إلى',
    arabic: 'العربية',
    hebrew: 'العبرية',
    typeAnswerIn: 'اكتب إجابتك بـ',
    answerIn: 'إجابة بـ',
    submitBtn: 'إرسال',
    yourAnswer: 'إجابتك',
    waitingFor: 'في انتظار',
    correctAnswer: 'الإجابة الصحيحة',
    answered: '✅ أجاب',
    thinking: '⏳ يفكر…',

    // Translation Duel
    translateTo: 'ترجم إلى',
    writeTranslationIn: 'اكتب ترجمتك بـ',
    yourTranslationIn: 'ترجمتك بـ',
    submitTranslation: 'إرسال الترجمة',
    yourTranslation: 'ترجمتك',
    translationOf: 'ترجمة',
    reference: 'مرجع',
    rateTranslation: 'قيّم ترجمة',
    close: 'قريب',
    good: 'جيد',
    perfect: 'مثالي',
    ratingsThisRound: 'تقييمات هذه الجولة',
    youGot: 'حصلت على',
    got: 'حصل على',
    nextRound: 'الجولة التالية قادمة…',
    submitted: '✅ أرسل',
    writing: '⏳ يكتب…',
  },

  en: {
    dir: 'ltr',
    langPickerTitle: 'App Language',
    langPickerSubtitle: 'Choose your language',
    langPickerContinue: 'Continue',
    hebrew: 'Hebrew',
    arabic: 'Arabic',
    skip: 'Skip',
    next: 'Next',
    joinMovement: 'Join the Movement 🌿',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign In',
    slides: [
      { title: 'Two peoples.\nOne world.', body: 'Israelis and Palestinians have lived side by side for generations — yet most have never had a real conversation. QOL changes that.' },
      { title: 'Connect across\nthe divide.', body: 'Discover real people on the other side. Swipe, match, and start a conversation — auto-translated so language is never a barrier.' },
      { title: 'Every message\nis a bridge.', body: "Peace doesn't start in parliaments. It starts with a simple 'hello' between two curious human beings." },
      { title: 'Safe.\nRespectful.\nReal.', body: 'QOL is built with strict safety features for minors and adults alike. A community rooted in mutual respect.' },
    ],
    signInTitle: 'Welcome back',
    signInSubtitle: 'Connecting people, bridging worlds',
    signInBtn: 'Sign In',
    signingIn: 'Signing in…',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm Password',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    signUpTitle: 'Create Account',
    signUpSubtitle: 'Join the QOL community',
    createAccount: 'Create Account',
    creatingAccount: 'Creating account…',
    ageDisclaimer: 'By registering you confirm you are at least 14 years old.',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    checkEmail: 'Check your email',
    otpSentTo: 'We sent a verification code to ',
    enterCode: 'Enter 6-digit code',
    verify: 'Verify',
    verifying: 'Verifying…',
    resendCode: 'Resend code',
    codeResent: 'Code resent!',
    continue: 'Continue',
    whatsYourName: "What's your name?",
    nameSubtitle: 'This is how other users will see you.',
    namePlaceholder: 'Your first name',
    whoAreYou: 'Who are you?',
    nationalitySubtitle: 'Your nationality sets the app language.',
    aboutYouTitle: 'About You',
    aboutYouSubtitle: 'Tell us a little about yourself.',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    dateOfBirth: 'Date of Birth',
    mustBe14: 'Must be at least 14 years old.',
    selectGender: 'Select gender',
    enterBirthdate: 'Enter birthdate',
    notOldEnough: 'Must be at least 14 to join QOL.',
    interestsTitle: 'Your Interests',
    interestsSubtitle: 'Pick at least 3 hobbies. They help you connect with people who share your passions.',
    selected: 'selected',
    needMore: 'more needed',
    yourProfileTitle: 'Your Profile',
    yourProfileSubtitle: 'Add a photo and bio so people can get to know you.',
    tapToAddPhoto: 'Tap to add profile photo',
    bioLabel: 'Bio',
    bioOptional: '(optional)',
    bioPlaceholder: 'A few words about you — hobbies, city, what you seek in a connection…',
    completeProfile: 'Complete Profile',
    skipForNow: 'Skip for now',
    discover: 'Discover',
    matches: 'Matches',
    games: 'Games',
    profile: 'Profile',
    matchesTitle: 'Matches',
    connections: 'connections',
    connection: 'connection',
    noMatchesYet: 'No matches yet',
    noMatchesMsg: 'Start swiping in the Discover tab to find your first cross-cultural connection!',
    goToDiscover: 'Go to Discover',
    newMatch: 'New Match!',
    miniGamesTitle: 'Mini Games',
    learnTogether: 'Learn a language with your match',
    chooseGame: 'Choose a game',
    pickMatch: 'Pick a match to play with',
    noMatchesForGame: 'You need at least one match to play!',
    noMatchesOnline: 'No matches online right now. Try again later!',
    selectGameHint: 'Select a game above to get started!',
    playWith: 'Play',
    twoPlayerGames: 'Two-Player Games',
    pendingInvites: 'Pending Invites',
    invitedYou: 'invited you to',
    acceptInvite: 'Accept & Play',
    waitingForOpponent: 'Waiting for opponent to join…',
    inviteSent: 'Invite sent to',
    cancel: 'Cancel',
    offlineGames: 'Single-Player Games',
    letterMatchName: 'Letter Match',
    letterMatchDesc: 'Drag Hebrew & Arabic letters into pairs — single player',
    matchLettersTitle: 'Letter Match',
    howToPlay: 'How to play:',
    howToPlayDesc: 'Drag each letter to its matching letter in the other language. Tap a letter to hear it. 3 mistakes ends the game.',
    gotIt: 'Got it!',
    youDidIt: 'You did it!',
    allMatched: 'All letters matched successfully.',
    playAgain: 'Play Again',
    youLost: 'You Lost',
    lostDesc: 'You made 3 mistakes. No worries, try again!',
    localTwoPlayerGames: 'Local Two-Player Games',
    memoryGameName: 'Memory Game',
    memoryGameDesc: 'Flip cards and match pairs — two players on the same device',
    memoryGameTitle: 'Memory Game',
    player: 'Player',
    player1: 'Player 1',
    player2: 'Player 2',
    playerTurn: 'Player turn',
    tie: 'Tie!',
    winner: 'Winner',
    yourTurn: 'Your turn!',
    profileTitle: 'Profile',
    signOut: 'Sign Out',
    aboutMe: 'About Me',
    interests: 'Interests',
    noBio: 'No bio yet. Tap ✏️ to add one.',
    noInterests: 'No interests yet.',
    appLanguage: 'App Language',
    writeSomething: 'Write something about yourself…',
    needThreeMore: 'more needed',
    minor: '🔒 Minor',
    adult: '✓ Adult',
    yearsOld: 'years old',
    hobbyTranslations: { Music: 'Music', Art: 'Art', Cooking: 'Cooking', Reading: 'Reading', Football: 'Football', Basketball: 'Basketball', Tennis: 'Tennis', Swimming: 'Swimming', Hiking: 'Hiking', Photography: 'Photography', Gaming: 'Gaming', Dancing: 'Dancing', Travel: 'Travel', Yoga: 'Yoga', Fitness: 'Fitness', Cinema: 'Cinema', Theatre: 'Theatre', Poetry: 'Poetry', Chess: 'Chess', Cycling: 'Cycling', Painting: 'Painting', Volunteering: 'Volunteering', Languages: 'Languages', History: 'History', Technology: 'Technology' },
    israeli: 'Israeli',
    palestinian: 'Palestinian',
    like: 'Like',
    pass: 'Pass',
    stillExploring: 'Still exploring hobbies',
    findingConnections: 'Finding connections…',
    wordGuessName: 'Word Guess',
    wordGuessDesc: 'Guess the word in the other language. Take turns!',
    translationDuelName: 'Translation Duel',
    translationDuelDesc: 'Translate a phrase — your partner rates your answer!',
    discoverTitle: 'Discover',
    meeting: 'Meeting',
    palestinians: 'Palestinians',
    israelis: 'Israelis',
    filter: 'Filter',
    all: 'All',
    sayHello: 'Say hello!',
    autoTranslated: 'Auto-translated.',
    youMetEveryone: "You've met everyone!",
    comeBackSoon: "You've gone through all available connections. New people join every day — check back soon!",
    refresh: 'Refresh',
    autoTranslatedMsg: 'Auto-translated',
    translationOff: 'Translation off',
    clearChat: 'Clear chat?',
    clearChatMsg: 'All messages will be permanently deleted for both users.',
    clear: 'Clear',
    writeHere: 'Write here…',
    opponent: 'Opponent',
    roundOf: 'Round',
    of: 'of',
    you: 'You',
    finalScore: 'Final Score',
    itsDraw: "It's a draw!",
    youWon: '🎉 You won!',
    goodGame: 'Good game!',
    opponentLeft: 'Opponent left the game',
    opponentLeftDesc: 'The game ended because the other player left.',
    backToGames: 'Back to Games',
    won: 'won',
    wordGuessGameName: '🔤 Word Guess',
    translationDuelGameName: '⚔️ Translation Duel',
    translateToLang: 'Translate this word to',
    typeAnswerIn: 'Type your answer in',
    answerIn: 'Answer in',
    submitBtn: 'Submit',
    yourAnswer: 'Your answer',
    waitingFor: 'Waiting for',
    correctAnswer: 'Correct answer',
    answered: '✅ Answered',
    thinking: '⏳ Thinking…',
    translateTo: 'Translate to',
    writeTranslationIn: 'Write your translation in',
    yourTranslationIn: 'Your translation in',
    submitTranslation: 'Submit Translation',
    yourTranslation: 'Your translation',
    translationOf: 'Translation of',
    reference: 'Reference',
    rateTranslation: "Rate translation of",
    close: 'Close',
    good: 'Good',
    perfect: 'Perfect',
    ratingsThisRound: 'Ratings this round',
    youGot: 'You got',
    got: 'got',
    nextRound: 'Next round coming…',
    submitted: '✅ Submitted',
    writing: '⏳ Writing…',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('qol_lang') || null);

  const chooseLang = (l) => {
    localStorage.setItem('qol_lang', l);
    setLang(l);
  };

  const t = translations[lang] || translations['he'];

  return (
    <LanguageContext.Provider value={{ lang, chooseLang, t, hasChosen: !!lang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}